# Generated by Django 3.2.6 on 2022-01-28 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='OTHERS', max_length=6),
        ),
    ]
